### ISSUE TITLE
Improve post service monitoring

### ISSUE THREAD

**Issue by WayneWayner** [xeliuqa/SM-Monitor#44]
Instead of pointing to each operator-address of each post service you could get all connected post services with their IDs, state and name from 
``grpcurl --plaintext localhost:9094 spacemesh.v1.PostInfoService.PostStates``

```
    {
      "id": "yourPubKey=",
      "state": "IDLE",
      "name": "ID_123.key"
    }
```

This would reduce sm-nodeList.txt config to only pointing to the fullnode instead of fullnode + n post services. Also you don't have to open up the unsafe operator interface on your machines.

**Comment by xeliuqa** [comment]
Main node will always show idle, regardless is post service is connected or not. This because main node does not tell you if service is connected, only the state. Idle/proving.
We'd have no way to tell if post service is successfully connected to main node. Now showing as !idle in red when not connected.

**Comment by Stizerg** [comment]
I'd love to do it as @WayneWayner says, but not possible atm.
