### ISSUE TITLE
RWD field not showing in tmux

### ISSUE THREAD

**Issue by chrcao** [xeliuqa/SM-Monitor#50]
version: v4.07

os: ubuntu 22

cmd:  tmux new -s sm-main-net pwsh sm-monitor.ps1

**Comment by xeliuqa** [comment]
Hi, can you elaborate more on the problem you are having?
Did you install PowerShell 7.+

**Comment by chrcao** [comment]
pt@pt:~/smh/tools/sm-monitor-4.07$ pwsh -v
PowerShell 7.4.2


cmd: pwsh sm-monitor.ps1
![1718022190052](https://github.com/xeliuqa/SM-Monitor/assets/3363370/446824af-71fa-415d-af43-cf7a428195b3)

cmd: tmux new -s sm-main-net pwsh sm-monitor.ps1
![1718022283874](https://github.com/xeliuqa/SM-Monitor/assets/3363370/d290e8a5-a048-4c59-a4f2-f9ff13ac264b)

**Comment by xeliuqa** [comment]
Ahh I see what you mean.
I also see that you've been messing with the code, so perhaps you deleted something you shouldn't?

**Comment by chrcao** [comment]
Thanks for making such a great tool, but I don't understand your question. Do you mean that I deleted the tip and it caused the problem?

![1718069867240](https://github.com/xeliuqa/SM-Monitor/assets/3363370/a2486af5-2a7e-4f9d-bb68-e78f2b66b1bb)

**Comment by Stizerg** [comment]
That is correct, it won't work without that message ;)
It's there, you just can't see it because of different colour palette and it set foreground colour the same as background.
If you dblclick to the place where should be the number it will be selected.
![image](https://github.com/xeliuqa/SM-Monitor/assets/105415949/827f7a95-fb98-46b0-9137-2b230d30825d)
![image](https://github.com/xeliuqa/SM-Monitor/assets/105415949/425aa736-8210-4e9c-b704-533549569342)
Try to change the colours of terminal
![image](https://github.com/xeliuqa/SM-Monitor/assets/105415949/f5a83be0-45e6-4548-a44f-0d0b2e7d6f40)

**Comment by Stizerg** [comment]
or around line 932 find this $foregroundColor = "DarkGray" and change that colour to what works for you
